### ISSUE TITLE
Helper function not working

### ISSUE THREAD

**Issue by butchewing** [pyaesone17/active-state#1]
This works for me:
`{{ Request::is('post') ? 'active' : 'no' }}`

This does not:
`{{ Active::check('data') }}`

This does not:
`{{ active_check('data') }}`

**Comment by pyaesone17** [comment]
@butchewing 

Could you provide me more detail.
What is the full Url you check ?

**Comment by butchewing** [comment]
I am running on localhost during development. I'm on Laravel 5.3

http://localhost:8888/dashboard

**Comment by pyaesone17** [comment]
You have to run 

php artisan vendor:publish .

The default value of the package rely on config/active.php.

Without configuration, you have to manually pass third and fourth parameters.

**Comment by butchewing** [comment]
Yes, I did previously run that.

```
➜  dashboard git:(master) ✗ php artisan vendor:publish
Copied Directory [/vendor/cartalyst/sentinel/src/migrations] To [/database/migrations]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied File [/vendor/maatwebsite/excel/src/config/excel.php] To [/config/excel.php]
Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]
Publishing complete for tag []!
```

**Comment by pyaesone17** [comment]
Did you register serviceprovider correctly ?
Seems like no config  file is published for my package. you can check this on config folder.
