### ISSUE TITLE
How to use with conditional blade?

### ISSUE THREAD

**Issue by garbinmarcelo** [pyaesone17/active-state#5]
Laravel 5.4
Homestead-7

I'm trying this:
```
@ifActiveUrl('painel/usuario')
    <li>Foo</li>
@endIfActiveUrl
```

But it returns me error:
`Parse error: syntax error, unexpected ''painel/usuario'' (T_CONSTANT_ENCAPSED_STRING) `

**Comment by pyaesone17** [comment]
@marcelogarbin 

I just released version 1.1.1.

Please download it and run "php artisan view:clear".
